# Generated by Django 6.0.3 on 2026-03-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_description_alter_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='cons',
            field=models.JSONField(blank=True, default=list, help_text="Elenco dei contro generati dall'AI"),
        ),
        migrations.AddField(
            model_name='review',
            name='pros',
            field=models.JSONField(blank=True, default=list, help_text="Elenco dei pro generati dall'AI"),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment',
            field=models.CharField(blank=True, help_text='Risultato analisi AI: positive, negative, neutral', max_length=10, null=True),
        ),
    ]
