# Generated by Django 6.0.3 on 2026-03-23 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_add_report_model'),
        ('reviews', '0004_reviewhelpfulvote'),
    ]

    operations = [
    ]
