# Generated by Django 6.0.3 on 2026-03-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('inactive', 'Inactive'), ('out_of_order', 'Out of Order')], default='inactive', max_length=20),
        ),
    ]
