# Generated by Django 6.0.3 on 2026-03-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ai_summary',
            field=models.JSONField(blank=True, help_text='Cached AI synthesis result', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='summary_last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
