# Generated by Django 6.0.3 on 2026-03-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_ai_summary_product_summary_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_hash', models.CharField(help_text="Sorted, concatenated string of product IDs (e.g., '1-4-5')", max_length=200, unique=True)),
                ('comparison_text', models.TextField(help_text='Cached comparison result with pros/cons')),
                ('winner_recommendation', models.TextField(help_text='AI winner recommendation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Product Comparison',
                'verbose_name_plural': 'Product Comparisons',
            },
        ),
    ]
